### PR TITLE
fix: cryto API is now imported with node namespace

### PR DESCRIPTION
**Pull request by RodrigoTomeES**
This fix the use of this library in Cloudflare workers

#1

### CODE REVIEW

**Comment by RodrigoTomeES** [comment]
fix #1

**Comment by RodrigoTomeES** [comment]
@zbauman3 could you review it? Thanks!

**Review by zbauman3 — APPROVED** [review]

**Comment by zbauman3** [comment]
@RodrigoTomeES I merged both of your PRs and release as `2.0.2`

**Comment by RodrigoTomeES** [comment]
Thanks! @zbauman3

**Pull request merged**
