### PR TITLE
Feature/web platform version

### LINKED ISSUE #1: Support Cloudflare workers (or any other worker)
Hi,

I think this would be possible replacing node crypto api with webcryto api:

```js
import { webcrypto } from 'node:crypto';
```

This will be awesome!

Update: I am working on a pr, only two test doesn't pass 👀

### PR DESCRIPTION
**Pull request by RodrigoTomeES**
fix #1

### CODE REVIEW

**Comment by RodrigoTomeES** [comment]
@zbauman3 I am wip to make it compatible with base64. Technically the code is compatible but it throws a different output than cryto node API. Do you have any ideas?

**Comment by RodrigoTomeES** [comment]
@zbauman3 can you review it?

**Comment by zbauman3** [comment]
@RodrigoTomeES sure thing, give me an hour or so and I'll take a look

**Comment by RodrigoTomeES** [comment]
@zbauman3 great, thanks!

**Review by zbauman3 — APPROVED** [review]
Nice work! This LGTM. 

I'll merge, but it's been a while since I released so that might take a bit. It looks like I have a few outdated dependencies too. I'll try to update those and do a release this weekend. 

Thanks for the contribution!

**Comment by zbauman3** [comment]
@RodrigoTomeES That ended up being easier to publish than I thought. I accidentally didn't exclude the new `.github` directory initially, so I re-released as `2.0.1` without it. 

Thanks again!

**Comment by RodrigoTomeES** [comment]
@zbauman3 nothing, you are welcome. Thanks for your quick review!

**Pull request merged**
